### ISSUE TITLE
Proper Attribution for MVP [8]

### ISSUE THREAD

**Issue by dmil** [code4policy/project#3]
Here is an example of a fleshed out user story (Part 2 of your story-time meeting):

**As a** creator of online content
**I want** to be properly attributed
**So that** I don't feel that someone else is taking credit for my work.

- [x] Independent
- [x] Negotiable
- [x] Valuable
- [x] Estimable
- [x] Small
- [x] Testable

(checking off this box indicates your team has discussed each item)

**Definitions of Done**
- [ ] We run the site by a casual reader and make sure they can find all of the citations easily.

**Tasks**
- [ ] We link out to any data-set or source that we mention in the text on the page
- [ ] Every visualization has a clear link to it's original source clearly visible near the visualization
- [ ] Proper citations for all of our sources at the bottom of the page as well
